openapi: 3.0.0
info:
  title: Test API
  description: This is a test API.
  version: 1.0.0
paths:
  /test:
    get:
      summary: A test endpoint
      responses:
        "200":
          description: Test successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Test successful"
